SET search_path TO USERMANAGEMENTAPI;

DROP TABLE IF EXISTS USERMANAGEMENTAPI.ROLE;

CREATE TABLE ROLE
(	
    ID 					SERIAL 	   		    NOT NULL, 
	CODE 				VARCHAR(10) 		NOT NULL,
	NAME 				VARCHAR(20) 		NOT NULL,
	DESCRIPTION			VARCHAR(100)		NOT NULL,
	CREATEDAT			TIMESTAMP(20)		NOT NULL,
	CONSTRAINT PK_TB_ROLE PRIMARY KEY (ID),
	CONSTRAINT UNIQUE_TB_ROLE_CODE  UNIQUE (CODE),
	CONSTRAINT UNIQUE_TB_ROLE_NAME  UNIQUE (NAME)
);