DROP TABLE IF EXISTS USERMANAGEMENTAPI.AUDITLOG;

CREATE TABLE AUDITLOG
(	
    ID 					SERIAL 	   		    NOT NULL, 
	ACTION 				VARCHAR(20) 		NOT NULL,
	ENTITY 				VARCHAR(20) 		NOT NULL,
	USERID				INTEGER				NOT NULL,
	TARGETID			INTEGER				NOT NULL,
	CREATEDAT			TIMESTAMP			NOT NULL,
	CONSTRAINT PK_TB_AUDITLOG PRIMARY KEY (ID),
	CONSTRAINT FK_TB_AUDITLOG_USERID FOREIGN KEY (USERID) REFERENCES USERMANAGEMENTAPI.USER(ID),
	CONSTRAINT FK_TB_AUDITLOG_TARGETID FOREIGN KEY (TARGETID) REFERENCES USERMANAGEMENTAPI.USER(ID)
);